# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad37b57762d6313297c1209a522d8df9"
name = "htm-app-one"
handle = "htm-app-one"
application_url = "https://testimony-close-arrest-chest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "htm-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://testimony-close-arrest-chest.trycloudflare.com/auth/callback",
  "https://testimony-close-arrest-chest.trycloudflare.com/auth/shopify/callback",
  "https://testimony-close-arrest-chest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
